[package]
name = "plainpaste"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
tao = "0.31.1"
tray-icon = "0.19.2"
winapi = { version = "0.3.9", features = ["windef", "winuser", "winbase"] }
windows-registry = "0.5.0"
windows-result = "0.3.1"
